let externalConfig = {}

const config = {
    // 全局变量
    color_brand_1: '#FE8F1D',
    color_brand_2: rgba('#FE8F1D', .9),
    color_brand_3: rgba(color_brand_1, .8),
    color_brand_4: rgba(color_brand_1, .7),
    color_brand_5: rgba(color_brand_1, .6),
    color_brand_6: rgba(color_brand_1, .5),
    color_brand_7: rgba(color_brand_1, .4),
    color_brand_8: rgba(color_brand_1, .3),
    color_brand_9: rgba(color_brand_1, .2),
    color_brand_10: rgba(color_brand_1, .1),
    color_gray_1: '#212121',
    color_gray_2: '#757575',
    color_gray_3: '#9E9E9E',
    color_gray_4: '#C4C4C4',
    color_gray_5: '#E0E0E0',
    color_gray_6: '#F2F2F2',
    color_gray_7: '#F5F5F5',
    color_gray_8: '#FAFAFA',
    //   color_gray_9: /,
    color_white: '#FFFFFF',
    color_black: '#000000',
    color_primary: color_brand_1,
    //   color_secondary:	/,
    color_business_red_1: '#FF2E2E',
    color_business_red_2: '#FF4E23',
    color_business_orange_1: '#FFA300',
    color_business_orange_2: '#FFEFD4',
    color_business_yellow_1: '#B97400',
    //   color_business_yellow_2: /,
    //   color_business_lightyellow_1: /,
    //   color_business_lightyellow_2: /,
    color_business_green_1: '#07C160',
    color_business_green_2: '#00BF7A',
    //   color_business_lightblue_1: /,
    //   color_business_lightblue_2: /,
    //   color_business_lightblue_3: /,
    color_business_blue_1: '#2A6AE9',
    color_business_blue_2: '#069DFF',
    color_business_purple_1: '#6236FF',
    //   color_business_purple_2: /,
    color_bg_white: rgba(__color_white, 1),
    color_bg_page: rgba(__color_gray_9, 1),
    color_bg_tab_default: rgba(__color_gray_7, 1),
    color_bg_disable: rgba(__color_gray_4, 1),
    color_bg_compo: rgba(__color_gray_5, 1),
    color_bg_notification: rgba(__color_business_orange_2, 1),
    color_text_primary: rgba(__color_primary, 1),
    color_text_1: rgba(__color_gray_1, 1),
    color_text_2: rgba(__color_gray_2, 1),
    color_text_3: rgba(__color_gray_3, 1),
    color_text_4: rgba(__color_gray_4, 1),
    color_text_inverse: rgba(__color_white, 1),
    color_text_inverse_secondary: rgba(__color_white ,.65),
    color_text_blue: rgba(__color_business_blue_2, 1),
    //   color_text_yellow: /,
    color_text_red: rgba(__color_business_red_1, 1),
    color_text_green: rgba(__color_business_green_1, 1),
    color_divider: rgba(__color_gray_6, 1),
    color_overlay_1: rgba(__color_black, .7),
    color_overlay_2: rgba(__color_white, .5),

    // 描边
    color_border_red_1: rgba(color_business_red_1, 1),
    //   color_border_red_2: /,
    color_border_green: rgba(color_business_green_1, 1),
    color_border_gray: rgba(color_gray_4, 1),
    color_border_blue: rgba(color_primary, 1),
    border_width_base: 1,
    border_radius_base: 2,
    border_radius_sm: calc(border_radius_base * 2),
    border_radius_m: calc(border_radius_base * 4),
    border_radius_l: calc(border_radius_base * 6),

    // 字体
    // font_family: 'PingFang SC'  'helvetica' 'Helvetica Neue' 'Microsoft Yahei',
    font_weight_base: 400,
    font_weight_medium: 600,
    // font_weight_bold: /,
    font_size_base: 16,
    font_size_sm_1: 14,
    font_size_sm_2: 12,
    // font_size_sm_3: /,
    // font_size_sm_4: /,
    // font_size_sm_5: /,
    // font_size_sm_6: /,
    font_size_header_1: 30,
    font_size_header_2: 28,
    font_size_header_3: 26,
    font_size_header_4: 24,
    font_size_header_5: 22,
    font_size_header_6: 20,
    font_size_header_7: 18,
    font_lineheight_base: 24,
    font_lineheight_sm_1: 20,
    font_lineheight_sm_2: 18,
    // font_lineheight_sm_3: /,
    // font_lineheight_sm_4: /,
    // font_lineheight_sm_5: /,
    // font_lineheight_sm_6: /,
    font_lineheight_header_1: 40,
    font_lineheight_header_2: 38,
    font_lineheight_header_3: 34,
    font_lineheight_header_4: 32,
    font_lineheight_header_5: 30,
    font_lineheight_header_6: 28,
    font_lineheight_header_7: 26,

    // 间距
    spacing_1: 4,
    spacing_2: spacing_1 * 2,
    spacing_3: spacing_1 * 3,
    spacing_4: spacing_1 * 4,
    spacing_5: spacing_1 * 5,
    spacing_6: spacing_1 * 6,
    spacing_7: spacing_1 * 7,
    spacing_8: spacing_1 * 8,
    spacing_9: spacing_1 * 9,
    spacing_10: spacing_1 * 10,
    width_icon_1: 12,
    width_icon_2: 16,
    // width_icon_3: /,

    // Button按钮
    radius_btn_m: border_radius_sm,
    radius_btn_s: border_radius_base,
    radius_btn_capsule_l: 24,
    radius_btn_capsule_m: 20,
    radius_btn_capsule_s: 16,
    width_btn_border: border_width_base,
    height_btn_l: 48,
    height_btn_m: 40,
    height_btn_s: 32,
    font_btn_size_l: font_size_header_7,
    font_btn_size_m: font_size_base,
    font_btn_size_s: font_size_sm_1,
    font_btn_lineheight_l: font_lineheight_header_7,
    font_btn_lineheight_m: font_lineheight_base,
    font_btn_lineheight_s: font_lineheight_sm_1,
    font_btn_link_size_m: font_size_base,
    font_btn_link_size_s: font_size_sm_1,
    font_btn_link_lineheight_m: font_lineheight_base,
    font_btn_link_lineheight_s: font_lineheight_sm_1,
    color_btn_font_inverse: rgba(color_text_inverse, 1),
    color_btn_font_primary_active: rgba(color_text_primary, 1),
    color_btn_font_primary_disable: rgba(color_text_inverse, 1),
    color_btn_font_default_active: rgba(color_text_2, 1),
    color_btn_font_default_disable: rgba(color_text_3, 1),
    color_btn_font_link_active: rgba(color_text_primary, 1),
    color_btn_font_link_gray: rgba(color_text_2, 1),
    color_btn_border_primary_active: rgba(color_primary, 1),
    color_btn_border_primary_disable: rgba(color_gray_3, 1),
    color_btn_border_default: rgba(color_gray_2, 1),
    color_btn_bg_transparent: transparent,
    color_btn_bg_default_active: rgba(color_white, 1),
    color_btn_bg_default_disable: rgba(color_white, 1),
    color_btn_bg_primary_active: rgba(color_primary, 1),
    color_btn_bg_primary_disable: rgba(color_gray_3, 1),
    color_btn_bg_secondary_active: rgba(color_brand_10, 1),
    color_btn_bg_gray: rgba(color_gray_7, 1),
    color_btn_icon_inverse: rgba(color_text_inverse, 1),
    color_btn_icon_primary_active: rgba(color_primary, 1),
    color_btn_icon_primary_disable: rgba(color_white, 1),
    color_btn_icon_default: rgba(color_gray_2, 1),
    color_btn_icon_disable: rgba(color_gray_3, 1),
    color_btn_icon_link_active: rgba(color_primary, 1),
    color_btn_icon_link_gray: rgba(color_gray_2, 1),
    width_btn_icon_l: 24,
    width_btn_icon_m: 20,
    width_btn_icon_s: width_icon_2,
    // width_btn_icon_loading_s: /,
    width_btn_icon_link_m: width_icon_2,
    width_btn_icon_link_s: 14,
    spacing_btn_paddingTop_l: spacing_3,
    spacing_btn_paddingBottom_l: spacing_3,
    spacing_btn_paddingLeft_l: 18,
    spacing_btn_paddingRight_l: 18,
    spacing_btn_paddingTop_m: 10,
    spacing_btn_paddingBottom_m: 10,
    spacing_btn_paddingLeft_m: spacing_4,
    spacing_btn_paddingRight_m: spacing_4,
    spacing_btn_iconOnly_paddingLeft_m: 10,
    spacing_btniconOnly_paddingRight_m: 10,
    spacing_btn_paddingTop_s: spacing_2,
    spacing_btn_paddingBottom_s: spacing_2,
    spacing_btn_paddingLeft_s: 14,
    spacing_btn_paddingRight_s: 14,
    spacing_btn_icon_padding_l: spacing_3,
    spacing_btn_icon_padding_m: spacing_2,
    spacing_btn_icon_padding_s: spacing_1,
    spacing_btn_icon_link_padding_m: spacing_2,
    spacing_btn_icon_link_padding_s: spacing_1,
    spacing_btn_group_paddingVertical_L: spacing_5,
    spacing_btn_group_paddingHorizontal_L: spacing_3,
    spacing_btn_group_paddingVertical_M: spacing_2,

    // Image图片
    image_width: 200,
    image_height: 200,
    image_radius: 0,
    image_bg_base: white,
    image_bg_default: gray_6,

    // Toast提示
    radius_toast: border_radius_sm,
    color_toast_bg: rgba(color_black, .7),
    color_toast_font_primary: rgba(color_text_inverse, 1),
    color_toast_font_secondary: color_text_inverse_secondary,
    color_toast_icon: rgba(color_white, 1),
    spacing_toast_base_paddingLeft: spacing_5,
    spacing_toast_base_paddingRight: spacing_5,
    spacing_toast_base_paddingTop: spacing_3,
    spacing_toast_base_paddingBottom: spacing_3,
    font_toast_base_size_title: font_size_base,
    font_toast_base_lineheight_title: font_lineheight_base,
    font_toast_base_size_subtitle: font_size_sm_4,
    font_toast_base_lineheight_subtitle: font_lineheight_sm_4,
    spacing_toast_base_title_padding: spacing_1,
    width_toast_base_icon: width_icon_2,
    spacing_toast_base_icon_padding: spacing_1,
    width_toast_square: 120,
    spacing_toast_square_paddingLeft: spacing_3,
    spacing_toast_square_paddingRight: spacing_3,
    spacing_toast_square_paddingTop: 30,
    spacing_toast_square_paddingBottom: 30,
    font_toast_square_size_title: font_size_sm_2,
    font_toast_square_lineheight_title: font_lineheight_sm_2,
    toast_vertical_text_maxlength: 120,
    width_toast_square_icon: 32,
    spacing_toast_bsquare_icon_padding: spacing_2,

    // popup 浮层面板
    spacing_popup_paddingLeft: spacing_4,
    spacing_popup_paddingRight: spacing_4,
    spacing_popup_paddingTop: spacing_4,
    spacing_popup_paddingBottom: spacing_3,
    // height_popup_down_min: 内容高度的1/4,
    // height_popup_down_max: 内容高度的3/4,
    radius_popup_down: 0,
    // height_popup_up_min: 内容高度的1/4,
    // height_popup_up_1: /,
    // height_popup_up_2: /,
    // height_popup_up_3: /,
    // height_popup_up_max: 内容高度的3/4,
    radius_popup_up_topLeft: 12,
    radius_popup_up_topRight: 12,
    // width_popup_horizontal_min: 内容宽度的2/5,
    // width_popup_horizontal_max: 内容宽度的4/5,
    width_popup_icon: width_icon_2,
    color_popup_icon: rgba(color_gray_4, 1),
    font_popup_title_size: font_size_header_4,
    font_popup_title_lineheight: font_lineheight_header_4,
    color_popup_title: rgba(color_gray_1, 1),
    font_popup_btn_size: font_size_base,
    size_popup_btn_lineheight: font_lineheight_sm_1,
    color_popup_btn_text_base: rgba(color_gray_1, 1),
    color_popup_btn_text_disable: rgba(color_text_4, 1),
    color_popup_btn_text_primary: rgba(color_text_primary, 1),
}

export default Object.assign({}, config, externalConfig || {})